# reference - https://spring.io/guides/gs/accessing-data-mysql/
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/D:/h2/anywhere
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create